config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :pages
  root :to => 'pages#index'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id            :integer          not null, primary key
#  visualiser_id :string(255)
#  settings      :text
#  user_id       :string(255)
#

class Setting < ActiveRecord::Base
  belongs_to :user
  serialize :settings, Hash
end

app/models/settings.rb
# == Schema Information
#
# Table name: settings
#
#  id            :integer          not null, primary key
#  visualiser_id :integer
#  settings      :string(255)
#  user_id       :string(255)
#

class Settings < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :settings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  private
  def authenticate_user
    if session[:user_id].present?
      @current_user = User.where(:id => session[:user_id]).first # Try to find a user but STAY CALM.
    end

    if @current_user.nil?
      session[:user_id] = nil
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_if_logged_in, :except => [:new, :create]
  before_action :check_if_admin, :only => [:index]

  def new
  end

  def create
    # binding.pry
    user = User.find_by(:username => params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      render json: user, :include => {:settings => {:only => [:visualiser_id, :settings]}}
    else
      render json: "Error"
    end
  end

  def destroy
    session[:user_id] = nil
    render nothing: true
  end

  private

  #chech if the user is logged in
  #loads the smart navs
  def check_if_logged_in
    redirect_to(new_user_path) if @current_user.nil?
  end

  #do we need this? I dont know. . .
  def check_if_admin
    redirect_to(root_path) unless @current_user.is_admin?
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def create
    visualiser_id = params[:settings][:visualiser]
    if oldsetting = @current_user.settings.find_by(visualiser_id: visualiser_id)
      oldsetting.update(settings: params[:settings][:setting].to_hash)
    else
      @setting = Setting.new(visualiser_id: visualiser_id, settings: params[:settings][:setting].to_hash, user_id: @current_user.id)
      if @setting.save
        @current_user.settings << @setting
      end
    end
    render json: @setting
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
    end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

    def index
      @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def smartnav
    links = "<div id='nav'><div id='inner-nav'>"
    if @current_user.try(:is_admin)
      links += "<div class='view-users-link'>" + link_to('View users', users_path) + "</div>"
    end

    if @current_user.present?
      links += "<div class='log-out-link'>"
      links += link_to('Logout ' + @current_user.username, session_path(@current_user.id), :data => {:method => :delete}, remote: true)
      links += "</div>"
    else
      links += "<div id='sign-up-link'><a href='/signup'>Sign Up</a></div>"
    end

    links + '</div>'
    links + '</div>'
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThreeDee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://connect.soundcloud.com/sdk.js' %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div id="container">
    <header>
      <div id="gh-btn">
        <iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=fork"
  allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
      </div>

      <h3 id="title"><a href="/">Threedee</a></h3>

      <%== smartnav %>
      <div class="sign-in-form">
        <%= form_tag(sessions_path, :id => "sign-in-ajax", :method => :post, remote: true) do %>
          <%= text_field_tag :username, nil, :placeholder => "Username" %>

          <%= password_field_tag :password, nil, :placeholder => "Password" %>

          <%= submit_tag "Sign In" %>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>Make You Wanna - Ta-Ku</p>
    </footer>
  </div><!--/////////////////////////close container //////////-->
</body>
</html>

app/views/pages/index.html.erb
<div class="index-container">
  <div id="popUpDiv">
    <h1>Welcome to THREEDEE!</h1>
    <p>An Interactive 3D Visualiser using Three.JS and WebAudioAPI.</p>
    <p>Click the right tab named 'Visual' to select, start and customise the visualiser.</p>
    <p>Click the left tab named 'Sound' to add your own songs, either with MP3 drag 'n' drop or a Soundcloud Link</p>
    <p><span id="warning">WARNING:</span> Don't use this app if you are prone to epileptic seizures.</p>
    <a href="#" id="popup" >Click to Close</a>
  </div>

  <div id="drop-zone">
    <h2>Drag n' Drop!</h2>
    <h4>Supported file types: mp3, wav, aiff, or ogg</h4>
  </div>
  <p id="upload" class="hidden">
    <label>Drag & drop not supported, but you can still upload via this input field:<br><input type="file"></label>
  </p>

  <div id="soundcloud-url">
    <h2>Soundcloud Paste n' Play!</h2>
    <div id="sc-url-content">
      <p>Find a track on <a href="http://www.soundcloud.com">http://www.soundcloud.com</a> and paste the URL below in the following format: http://soundcloud.com/artist/track.</p>
      <input type="url" placeholder="(http://soundcloud.com/artist/track)">
      <p class="disclaimer">Soundcloud playlist links are currently not supported and will break. Sorry.</p>
    </div>
  </div><!--///////////// close soundcloud-url ////////-->

  <div id="visualiser-canvas"></div><!--///////////close visualiser ////////-->

  <div id="player"></div><!--//////////// player //////////-->
</div>


<div id="sidebar-container">
  <div class="sound-panel">
    <a class="sound-tab" href="#">
    <div id="span-container">
      <span>S</span>
      <span>O</span>
      <span>U</span>
      <span>N</span>
      <span>D</span>
    </div>
    </a>
    <div class="under-color">
      <div id="mp3-drop-menu">MP3 DROP</div>
    </div>
    <div class="under-color">
      <div id="soundcloud-menu">SOUNDCLOUD URL</div>
    </div>
  </div><!--///////////// close sound-panel ////////-->

  <div class="vis-panel">
    <a class="vis-tab" href="#">
    <div id="span-container">
      <span>V</span>
      <span>I</span>
      <span>S</span>
      <span>U</span>
      <span>A</span>
      <span>L</span>
    </div>
    </a>

      <select name="visualisers" id="visualisers_list">
      <option value="sunflare">sunflare</option>
      <option value="lines">lines</option>
      <option value="cubeGrid">cubeGrid</option>
      </select><!--///////////// close select menu ////////-->

     <div id="controllsList">
      <form id="linesSpeedControls">
        <ul>
          <li>SpeedX:<br><input type="range" id="speedControlX" name="speedControlX" min="-3.9" max="10.0"></li>
          <li>SpeedY:<br><input type="range" id="speedControlY" name="speedControlY" min="-3.9" max="10.0"></li>
          <li>SpeedZ:<br><input type="range" id="speedControlZ" name="speedControlZ" min="-3.9" max="10.0"></li>
          <li id="line-thick">Line Thickness:<br><input type="range" id="lineWidthControler" name="lineWidthControler" min="-0.9" max="10.0"></li>
          <li id="line-backcolor">Background Color: <input type="color" id="backgroundColorControl" name="backgroundColorControl"></li>

          <input value="Start" type="submit" id="linesSubmit">
          <input type="submit" id="lines-save" value="Save" class="save-button">
        </ul>
      </form><!--////////////////// close form linesSpeedControls//////////-->

      <form id="sunflareControls">
        <ul>
          <li>Rotation SpeedY: <input type="range" id="sunflare-rotationX" name="sunflare-rotationX" min="-50" max="50"></li>
          <li>Rotation SpeedX: <input type="range" id="sunflare-rotationY" name="sunflare-rotationY" min="-50" max="50"></li>
          <li>Type of Star: <input type="range" id="sunflare-size" min="1" max="120"></li>

          <input value="Start" type="submit" id="sunflareSubmit">
          <input type="submit" id="sunflare-save" value="Save" class="save-button">

        </ul>
      </form><!--////////////////// close form sunflareControls//////////-->

      <form id="cubeGridControls">
        <ul>
          <li>Particle Number: <input type="range" id="particleNumber" min="10" max="500"></li>
          <li>Particle Speed Base: <input type="range" id="particleSpeedBase" min="10" max="150"></li>
          <li>Particle Speed Spread: <input type="range" id="particleSpeedSpread" min="0" max="200"></li>

          <li id="cube-strength">Cube Strength: <input type="range" id="cubeStrength" min="1" max="50"></li>
          <li id="cube-text">Text: <input type="text" id="cubeYourText"></li>
          <li id="cube-backcolor">Background Color: <input type="color" id="cubeBackgroundColorControl"></li>
          <li id="cube-textcolor">Text Color: <input type="color" id="cubeText3dColor"></li>

          <input value="Start" type="submit" id="cubeGridSubmit">
          <input type="submit" id="cubegrid-save" value="Save" class="save-button">
        </ul>
      </form><!--////////////////// close form cubeGridControls//////////-->
    </div><!--////////////////// close controllsList //////////-->
  </div><!--///////////// close vis-panel ////////-->

</div><!--///////////// close sidebar-container ////////-->

app/views/session/new.erb
<div id="loginpage">
<div id="logintext">
</div><!--//////////// close login text ////// -->

<div id="loginline">
</div><!--//////////// close loginline ////// -->


<div id="login">

  <h3>SIGN IN:</h3>

<%= form_tag('/login') do %>
<h2><%= label_tag :username, "Username:" %>
<%= text_field_tag :username %>
</h2>

<h2><%= label_tag :password, "Password:" %>
<%= password_field_tag :password %>
</h2>

<%= submit_tag 'submit' %>

<% end %>

</div><!-- /////// close login //////-->

</div><!-- /////// close loginpage //////-->

app/views/settings/create.html.erb
<h1>Settings#create</h1>
<p>Find me in app/views/settings/create.html.erb</p>

app/views/users/_form.erb
<div id="signup">
      <h2>Sign Up</h2>
      <%= form_for @user do |f| %>
        <h3>
        <%= f.text_field :username, :autofocus => true, :placeholder => "Username" %>
        </h3>

        <h3>
        <%= f.password_field :password, :placeholder => "Password"%>
        </h3>

        <h3>
        <%= f.password_field :password_confirmation, :placeholder => "Confirm Password"%>
        </h3>

        <%= f.submit %>
      <% end %>
</div><!--/////// close signup //////-->

app/views/users/new.erb
<%= render :partial => 'form' %>